# inactive-opacity = 0.8;
# frame-opacity = 0.7;

shadow = false;

fading = false;

# backends: `xrender`, `glx`, `egl` or `xr_glx_hybrid`
backend = "glx";

dithered-present = false;
vsync = true;
detect-rounded-corners = false
use-ewmh-active-win = true
detect-transient = true;
use-damage = true;
log-level = "warn";

